version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: unidir
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4321
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    restart: on-failure
    links:
      - db

volumes:
  pgdata:
